name: Robot Framework Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: hsl/robot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright dependencies
      run: |
        npm install
        npx playwright install --with-deps
      working-directory: C:\hostedtoolcache\windows\Python\3.12.8\x64\Lib\site-packages\Browser\wrapper

    - name: Run Robot Framework tests
      run: |
        robot -d ./results -v APIKEY:${{ secrets.DIGITRANSIT_APIKEY }} -v HEADLESS:True tests

    - name: Upload Robot Framework results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: hsl/robot/results/
        retention-days: 30