name: Robot Framework Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Robot Framework tests
      run: |
        pwd
        tree
        sudo mkdir ${{ github.workspace }}/hsl/robot/reports && sudo chmod -R 777 ${{ github.workspace }}
        docker run --rm \
          -v /home/runner/work/miscellaneous-stuff/miscellaneous-stuff/hsl/robot/ci-requirements.txt:/opt/robotframework/pip-requirements.txt:Z \
          -v /home/runner/work/miscellaneous-stuff/miscellaneous-stuff/hsl/robot/reports:/opt/robotframework/reports:Z \
          -v /home/runner/work/miscellaneous-stuff/miscellaneous-stuff/hsl/robot:/opt/robotframework/tests:Z \
          -e ROBOT_OPTIONS="-d /opt/robotframework/reports" \
          -e ROBOT_OPTIONS="-e hsl" \
          -e ROBOT_OPTIONS="-v APIKEY:${{ secrets.DIGITRANSIT_APIKEY }}" \
          --user $(id -u):$(id -g) \
          ppodgorsek/robot-framework:latest

    - name: Upload Robot Framework results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: ${{ github.workspace }}/hsl/robot/reports
        retention-days: 30