name: Robot Framework Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: hsl/robot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        rfbrowser init

    - name: Run Robot Framework tests
      run: |
        robot -d ./results -v APIKEY:${{ secrets.DIGITRANSIT_APIKEY }} -v HEADLESS:True tests

    - name: Upload Robot Framework results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: hsl/robot/results/
        retention-days: 30